# name: CI/CD Pipeline

# on:
#   push:
#     branches: [ main, master ]
#   pull_request:
#     branches: [ main, master ]

# jobs:
#   test:
#     runs-on: ubuntu-latest
    
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4
      
#     - name: Setup Node.js
#       uses: actions/setup-node@v4
#       with:
#         node-version: '20'
#         cache: 'npm'
        
#     - name: Install dependencies
#       run: npm ci
      
#     - name: Run tests
#       run: npm test
      
#     - name: Run tests with coverage
#       run: npm run test:coverage
      
#     - name: Upload coverage reports
#       uses: codecov/codecov-action@v3
#       with:
#         file: ./coverage/lcov.info
#         flags: unittests
#         name: codecov-umbrella

#   deploy-aws:
#     needs: test
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4
      
#     - name: Setup Node.js
#       uses: actions/setup-node@v4
#       with:
#         node-version: '20'
#         cache: 'npm'
        
#     - name: Install dependencies
#       run: npm ci
      
#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v4
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: us-east-1
        
#     - name: Deploy to Elastic Beanstalk
#       uses: einaregilsson/beanstalk-deploy@v21
#       with:
#         aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         application_name: ngback-api
#         environment_name: ngback-api-prod
#         version_label: ${{ github.sha }}
#         region: us-east-1
#         deployment_package: ./
#         use_existing_version_if_available: false 